# Generated by Django 5.0.7 on 2024-08-16 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoFinal', '0003_disco'),
    ]

    operations = [
        migrations.AddField(
            model_name='disco',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='discos/'),
        ),
    ]
